config/routes.rb
Rails.application.routes.draw do
  resources :dataobjs

end

app/models/dataobj.rb
class Dataobj < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dataobjs_controller.rb
class DataobjsController < ApplicationController
  before_action :set_dataobj, only: [:show, :edit, :update, :destroy]

  # GET /dataobjs
  # GET /dataobjs.json
  def index
    @dataobjs = Dataobj.all
  end

  # GET /dataobjs/1
  # GET /dataobjs/1.json
  def show
  end

  # GET /dataobjs/new
  def new
    @dataobj = Dataobj.new
  end

  # GET /dataobjs/1/edit
  def edit
  end

  # POST /dataobjs
  # POST /dataobjs.json
  def create
    @dataobj = Dataobj.new(dataobj_params)

    respond_to do |format|
      if @dataobj.save
        format.html { redirect_to @dataobj, notice: 'Dataobj was successfully created.' }
        format.json { render :show, status: :created, location: @dataobj }
      else
        format.html { render :new }
        format.json { render json: @dataobj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dataobjs/1
  # PATCH/PUT /dataobjs/1.json
  def update
    respond_to do |format|
      if @dataobj.update(dataobj_params)
        format.html { redirect_to @dataobj, notice: 'Dataobj was successfully updated.' }
        format.json { render :show, status: :ok, location: @dataobj }
      else
        format.html { render :edit }
        format.json { render json: @dataobj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dataobjs/1
  # DELETE /dataobjs/1.json
  def destroy
    @dataobj.destroy
    respond_to do |format|
      format.html { redirect_to dataobjs_url, notice: 'Dataobj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dataobj
      @dataobj = Dataobj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dataobj_params
      params.require(:dataobj).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dataobjs_helper.rb
module DataobjsHelper
end

app/views/dataobjs/_form.html.erb
<%= form_for(@dataobj) do |f| %>
  <% if @dataobj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dataobj.errors.count, "error") %> prohibited this dataobj from being saved:</h2>

      <ul>
      <% @dataobj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dataobjs/edit.html.erb
<h1>Editing Dataobj</h1>

<%= render 'form' %>

<%= link_to 'Show', @dataobj %> |
<%= link_to 'Back', dataobjs_path %>

app/views/dataobjs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dataobjs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dataobjs.each do |dataobj| %>
      <tr>
        <td><%= dataobj.name %></td>
        <td><%= dataobj.description %></td>
        <td><%= link_to 'Show', dataobj %></td>
        <td><%= link_to 'Edit', edit_dataobj_path(dataobj) %></td>
        <td><%= link_to 'Destroy', dataobj, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dataobj', new_dataobj_path %>

app/views/dataobjs/new.html.erb
<h1>New Dataobj</h1>

<%= render 'form' %>

<%= link_to 'Back', dataobjs_path %>

app/views/dataobjs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dataobj.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dataobj.description %>
</p>

<%= link_to 'Edit', edit_dataobj_path(@dataobj) %> |
<%= link_to 'Back', dataobjs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestfulRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>